### ISSUE TITLE
Cannot publish package

### ISSUE THREAD

**Issue by josephmancuso** [girardinsamuel/masonite-inertia#15]
Getting this error:

```
$ python craft publish InertiaProvider --tag demo
  AttributeError

  'NoneType' object has no attribute 'items'

**Comment by girardinsamuel** [comment]
Yeah for the fro I did not really used it. 
The package is working but publishing a demo is not working for now..

**Comment by girardinsamuel** [comment]
it has already been reported here 
https://github.com/girardinsamuel/masonite-inertia/issues/3.

I am closing this one then.
